### ISSUE TITLE
如何在label中的元素添加事件？

### ISSUE THREAD

**Issue by codepandy** [jser-club/rc-bmap#100]
需要实现的是一个提示内容，所以我给label传递了html字符串，但是里面有一个button，button需要一个点击事件，这个事件如何调用组件中定义的事件？
如果用比较react的方式来处理？

###目前解决方法
`<div onclick='onClick()'>hello</div>`
```
window.onClick=()=>{}
```

有没有一个比较react的方式来解决。

**Comment by JserWang** [comment]
嗨，`label`中的`content`百度的官方用类似`document.write`方式进行写入的，所以没有办法使用相对`react`的方式来实现，但`infowindow`中的`title`与`content`是通过`appendChild`的方式实现的，所以可以用`react`的方式来进行事件绑定。对此，我们也只能期待百度地图内部的升级。
