### ISSUE TITLE
setMapStyle

### ISSUE THREAD

**Issue by JustLikeU** [jser-club/rc-bmap#109]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run. Paste the link to your CodeSandbox (https://codesandbox.io/s/jnnxrwq5y3) example below:**

**What is the expected behavior?**

**Comment by JustLikeU** [comment]
没有看到这个api

**Comment by JserWang** [comment]
http://jser.wang/bmap/components/map

搜关键字 mapStyle、mapStyleV2，该如何用写的很清楚了，如果有问题可以再重新打开`issuse`与我取得联系。
