### ISSUE TITLE
请问有热力图组件吗

### ISSUE THREAD

**Issue by JustLikeU** [jser-club/rc-bmap#110]
如题

**Comment by JserWang** [comment]
预计明天发布的`1.0.4`版本，会有热力图组件，目前还在整理中，添加完成还要继续补充文档，还请耐心等待。

**Comment by JserWang** [comment]
嗨，`1.0.4`目前已发布，热力图组件可以参考示例：
[http://jser.wang/bmap/examples/library/heatmap](http://jser.wang/bmap/examples/library/heatmap)

文档稍后发布

**Comment by JustLikeU** [comment]
赞！
