### ISSUE TITLE
0.2.4版本的说明文档怎么不能访问了？

### ISSUE THREAD

**Issue by codepandy** [jser-club/rc-bmap#116]
0.2.4文档地址:
https://bmap.jser-club.com

上面的地址不能访问了，能否放开呢，由于历史原因，无法重构使用新版本组件，所以很多工作还需要查看老版本的文档。

**Comment by codepandy** [comment]
@JserWang 
这个版本的说明文档还能让继续访问吗？

**Comment by JserWang** [comment]
hi， @codepandy 现可以通过`http://jser.wang/bmap0.24/` 进行访问

**Comment by codepandy** [comment]
@JserWang 
嗯，太感谢了！
