### ISSUE TITLE
某些this.setState({}) 导致  Marker 回到最初的point

### ISSUE THREAD

**Issue by heerey525** [jser-club/rc-bmap#120]
https://codesandbox.io/s/rcbmapsampledemo-62w5x
需求：在input输入地址（address）在地图上显示
问题：在输入过程中，this.setState({ address })，导致Marker移动到point初始位置
希望解决：其他this.setState({}) 不干扰 Marker

**Comment by imyar** [comment]
我也遇见了，如何解决啊？ @JserWang
