### ISSUE TITLE
Polyline.IconSequence 折线符号 渲染之后拖拽地图导致Symbol偏移

### ISSUE THREAD

**Issue by Lpbzzz** [jser-club/rc-bmap#128]
http://jser.wang/bmap/components/polyline 文档中能看到效果 浏览器是最新版chrome 64位 win10

**Comment by Lpbzzz** [comment]
大概300个点的样子
![路径](https://user-images.githubusercontent.com/28721487/62109932-e622c400-b2df-11e9-9c74-3a6f99be733a.png)

**Comment by JserWang** [comment]
由于rc-bmap仅作为百度地图的React封装，此处为百度地图官方bug，在一个多月前我就已经向百度地图反馈过，至今他们还没修复。 目测是拖拽后折线位置算法问题。

**Comment by Lpbzzz** [comment]
> 由于rc-bmap仅作为百度地图的React封装，此处为百度地图官方bug，在一个多月前我就已经向百度地图反馈过，至今他们还没修复。 目测是拖拽后折线位置算法问题。

好的！谢谢！
