### ISSUE TITLE
point lng lat 为 0

### ISSUE THREAD

**Issue by Lpbzzz** [jser-club/rc-bmap#129]
当lng lat为0的时候会报错。实际上 （0,0） 有可能是一种需求

**Comment by JserWang** [comment]
您好，请问有具体报错截图吗？或者您是否能提供下应用场景，在什么情况下会使用到`0, 0`，我们可以一起探讨下。

**Comment by Lpbzzz** [comment]
这个例子我用【http://jser.wang/bmap/examples/overlay/normal】复现了一下：
①设置地图中心点位 (0,0)
②把覆盖物的位置也是(0,0) 
③将覆盖物添加到地图；报错：
![wwxx](https://user-images.githubusercontent.com/28721487/63249304-cad22580-c29b-11e9-8f90-8dde8b65fed4.png)

因为我的数据是从后端获取的，有的时候后端为了防止null会设置(0,0)所以偶尔会碰到。现在我自己在接收数据的时候把(0,0,)重置掉了，所以其实也没什么大影响。

**Comment by Lpbzzz** [comment]
可能修改一下判断条件就ok吧？

**Comment by JserWang** [comment]
我在1.0.5修改了判断，现在只要是数字类型即可使用。
