### ISSUE TITLE
如何获取Map组件的实例

### ISSUE THREAD

**Issue by niuchunling** [jser-club/rc-bmap#138]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run. Paste the link to your CodeSandbox (https://codesandbox.io/s/jnnxrwq5y3) example below:**

**What is the expected behavior?**

**Comment by niuchunling** [comment]
找到了办法
<Map name="mapName " />
地图实例：window.mapName   (rc-bmap实例化后，自动将实例加到window上)
调用地图原生方法地图：new window.BMap.DrivingRoute(window.mapName )

**Comment by JserWang** [comment]
在`<Map>`标签中，添加`name`属性即可
