### ISSUE TITLE
scroll Zoom 缩放bug

### ISSUE THREAD

**Issue by dalaoque** [jser-club/rc-bmap#54]
当body有scroll动作后，地图缩放中心点不在是鼠标，偏离很远。

**Comment by JserWang** [comment]
您好，可否提供部分代码片段来帮助我们快速定位问题？

这里有Map的相关示例，供参考：
https://bmap.jser-club.com/examples/

**Comment by dalaoque** [comment]
我把地图渲染在antd Modal 弹出框中，  当在body scroll后，此时弹出的地图再通过鼠标scroll，缩放中心是偏离鼠标位置的。  

请问有源码下载地址吗？我在jsfiddle复现一下

**Comment by Moocliu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    

git clone https://github.com/JserWang/rc-bmap.git
cd rc-bmap
git checkout dev
npm run build # 这时，您可以看到最新的开发版本lib 也可以修改的源码


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }

        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
                                
            
                
                    
                            
                                
                            
                            
                                namocliu
                            
                    
                        
                            
                                    namocliu@gmail.com
                            
                        
                
            
        
                    
                
                
                    签名由
                    网易邮箱大师
                    定制
                
 


    在2018年8月21日 15:57，Smile John<notifications@github.com> 写道： 


我把地图渲染在antd Modal 弹出框中，  当在body scroll后，此时弹出的地图再通过鼠标scroll，缩放中心是偏离鼠标位置的。
请问有源码下载地址吗？我在jsfiddle复现一下

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by JserWang** [comment]
很抱歉，之前忽略了把压缩后的js上传到cdn这件事情，已经在刚才进行了处理。
您可以通过引用以下链接即可：

https://unpkg.com/rc-bmap@0.2.2/dist/rc-bmap.min.js

**Comment by dalaoque** [comment]
嗨～，bug复现请查看：

https://jsfiddle.net/dalaoque/phb1o5nv/37/

**Comment by JserWang** [comment]
感谢您提供的示例，此处是由于map的父容器`position: 'fixed'`所导致的，这是百度地图内部的一个bug。不过在此我建议您可以通过`absolute`+`scroll` 模拟出`fixed`的效果，可以避免。我已像百度提了相应的工单，若官方有结论时，我会第一时间同步您。

感谢您对我们的支持。

**Comment by JserWang** [comment]
目前百度工程师还在测试`position: fixed`的问题，这个issue我先关了，如果有需要的时候，可以再reopen。
