### ISSUE TITLE
RidingRoute的onSearchComplete没执行

### ISSUE THREAD

**Issue by codepandy** [jser-club/rc-bmap#66]
我想获取规划路径的坐标数组，但是onSearchComplete事件没执行，如下code：
···
 <WalkingRoute
            getInstance={this.getRoute}
            showInMap
            location="北京"
            onSearchComplete={this.onSearchComplete}
            // 这里还有更多属性，可参考文档
          />
···

但是我通过在`mapMounted`事件中给route绑定一个方法能获取到
···
route.onSearchComplete=res=>{
console.log(res);
}
···
第一种方式也不错吧，是我调用的问题吗？

能否获取到规划路径的坐标数组？我看上面返回的只是起点和终点两个位置对象。

随便问下，能否让规划路径显示成虚线，这也是我要坐标数组的目的，如果不能，我就拿这些点自己画点来当虚线用。

**Comment by JserWang** [comment]
首先：
onSearchComplete写在render中，是可用的，可直接参考示例中代码。

https://codesandbox.io/s/ymv7n67wrz

其中L21-L29
```
  onSearchComplete = result => {
    console.log(result);
    const plan = result.getPlan(0); // 取第一条方案
    console.log(plan.getDistance()); // 取当前方案距离
    console.log(plan.getDuration()); // 取当前方案耗时
    const route = plan.getRoute(0); // 取当前路线
    console.log(route);
    const path = route.getPath(); // 当前路线坐标集合
    console.log(path);
  };
```

这个path，就是最终您想要的当前展现路线中的坐标集合。

**Comment by codepandy** [comment]
非常感谢您的回答，我知道我的为什么没出来了，我一个walkingRoute，下面还有一个RidingRoute，我只是写了上面一个的事件，下面的没写，所以就没执行
```
<WalkingRoute
            getInstance={this.getRoute}
            showInMap
            location="北京"
            onSearchComplete={this.onSearchComplete}
            // 这里还有更多属性，可参考文档
          />
          <RidingRoute
            getInstance={this.getRoute}
            showInMap
          />
```
下一个组件的onSearchComplete会覆盖上面的一个，按说两个应该互不影响才对吧。这算不算个bug？
下面是我的验证，下面的果然会覆盖上面的。
```
<WalkingRoute
            getInstance={this.getRoute}
            showInMap
            location="北京"
            onSearchComplete={this.onSearchComplete}
            // 这里还有更多属性，可参考文档
          />
          <RidingRoute
            getInstance={this.getRoute}
            showInMap
            onSearchComplete={this.onSearchComplete1}
          />



 onSearchComplete = result => {
    console.log('aaaaaaaaaa');
    console.log(result);
  };

  onSearchComplete1 = result => {
    console.log('bbbb');
    console.log(result);
  };
```
结果只输出了bbb和下面的对象，没有aaaa。

**Comment by JserWang** [comment]
这是使用时的问题。

我修改了示例中的代码：
https://codesandbox.io/s/ymv7n67wrz

上面产生的原因是由于在组件中的`getInstance`中，`route`后者覆盖了前者，这个`searchComplete`是通过`route.search`触发的，所以，在示例中，我用了更明确的名字来标识当前组件。看眼示例，您就都明白了。

**Comment by codepandy** [comment]
嗯，明白了，厉害厉害
