### ISSUE TITLE
地图上没有地区搜索功能？

### ISSUE THREAD

**Issue by zhangqi053694** [jser-club/rc-bmap#70]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run. Paste the link to your CodeSandbox (https://codesandbox.io/s/jnnxrwq5y3) example below:**

**What is the expected behavior?**

**Comment by JserWang** [comment]
请详细描述下您的问题好嘛？想要怎样的搜索？
