### ISSUE TITLE
地图在进行定位时会报错

### ISSUE THREAD

**Issue by elliot-cj** [jser-club/rc-bmap#74]
地图在进行定位时会报错： Uncaught TypeError: Cannot read property 'address' of null

![2018-10-20_014307](https://user-images.githubusercontent.com/24952426/47234819-a1d9cd80-d409-11e8-98fb-2bf88fa50ae9.png)

**Comment by elliot-cj** [comment]
直接用示例中的定位也会报错，求解

**Comment by JserWang** [comment]
地图定位是百度地图自带的行为，请问现在还报错吗？

**Comment by gengdz** [comment]
> 地图定位是百度地图自带的行为，请问现在还报错吗？

今天我在Chrome浏览器中，使用示例中定位功能的时候也会报错，报错信息同上。但是，这个错误在edge浏览器中没有发现。
![image](https://user-images.githubusercontent.com/41912568/51422907-5c889000-1bf2-11e9-9279-99696d63761a.png)
![image](https://user-images.githubusercontent.com/41912568/51422915-7f1aa900-1bf2-11e9-85a4-c809ae862807.png)
但是我在Chrome浏览器中使用百度地图官网的定位功能是没有问题的，请开发者大大能不能给个解决方法。以为我已经在项目中使用了rc-bmap ，并且即将使用到定位功能。
同时。我想请问一下，如果用户不点击定位图标，我怎么拿到他当前的坐标？

**Comment by JserWang** [comment]
@gengdz 嗨，目前 `1.0.0`版本源码部分已经重构完成，全新源码、全新的demo、全新的文档，目前处于文档补全阶段，预计在这个周末就会发布。关于你上面的问题，如果想在当前版本解决的话，可以参考下目前next分支的  `core/utils/map.js ` 中的 `getCurrentPosition ` 的实现，链接如下：[https://github.com/jser-club/rc-bmap/blob/next/src/core/utils/map.js#L149#L161](https://github.com/jser-club/rc-bmap/blob/next/src/core/utils/map.js#L149#L161)

至于上面关于chrome版本的定位问题，可以看下chrome是否禁用了获取位置信息。

**Comment by gengdz** [comment]
@JserWang 很开心你能这么快回我，我已经确认不是禁用了获取位置信息的原因。另外，如果这周有版本更新的话，我可以在我的项目中使用新版本，因为目前只有我一个人在项目中使用了rc-bmap。并且距离我这个功能的交付还有一两周的时间。

**Comment by JserWang** [comment]
@gengdz OK，我会尽快完善完文档发布，明天的这个时间可以留意下官网的变化，如果在将来使用有任何问题时，随时可以通过issue与我取得联系。

**Comment by gengdz** [comment]
@JserWang 好的，辛苦了。
