### ISSUE TITLE
定位是报错?

### ISSUE THREAD

**Issue by qihui1223** [jser-club/rc-bmap#78]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run. Paste the link to your CodeSandbox (https://codesandbox.io/s/jnnxrwq5y3) example below:**

**What is the expected behavior?**

**Comment by qihui1223** [comment]
Cannot read property 'address' of null

**Comment by qihui1223** [comment]
显示Cannot read property 'address' of null 
直接用示例也是这个错误

**Comment by JserWang** [comment]
The same to #74
