### ISSUE TITLE
如何根据地名获取坐标信息？

### ISSUE THREAD

**Issue by codepandy** [jser-club/rc-bmap#79]
我想根据一个地址名称，获取到他的坐标，并且不需要在页面中显示地图，通过实例的方式获取到就行。
这个怎么弄呢？

**Comment by JserWang** [comment]
百度有一个类叫 LocalSearch

在当前版本您可以暂时自己使用LocalSearch进行查询，不依赖地图的情况下，举个例子：

```
const local = new window.BMap.LocalSearch("北京市", {
   onSearchComplete(result) {
       console.log(result.getPoi(0))
   }
});

local.search("百度大厦");

```
在下个版本中，会将类似上述代码改为Promise的形式稍微包装一下，作为Util方法暴露给开发者。

**Comment by JserWang** [comment]
@codepandy 关于LocalSearch的返回结果，可参考：
http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference_3_0.html#a7b4

**Comment by JserWang** [comment]
另外，如果单纯的想拿到地址的话，可以通过百度提供的  Geocoder 类。

**Comment by JserWang** [comment]
https://github.com/jser-club/rc-bmap/blob/1e040f89649c38892c03adf1e3c91a47252a4f72/src/core/utils/map.js#L187#L198

可以看next分支对应的实现。

**Comment by codepandy** [comment]
嗯，好的，谢谢，辛苦了
