### ISSUE TITLE
使用 “AutoComplete” 组件，onconfirm回调方法里怎么获取当前选中项的Point(lng,lat)属性

### ISSUE THREAD

**Issue by zxyty** [jser-club/rc-bmap#81]
如下代码，我怎么在`onconfirm`方法里获取当前选中项的经度和纬度，用于在地图上进行标记显示
```js
...
const events = {
  onconfirm(e) {
    console.log(e);
  }
};
...
<AutoComplete
  input="pcc"
  searchComplete={this.searchComplete}
  events={events}
  location={location}
  value={value}
/>
```

**Comment by JserWang** [comment]
这里可以通过`onconfirm`中的`e`取得所选地址：
```
cosnt valObj = e.item.value;
const target = `${valObj.province}${valObj.city}${valObj.district}${valObj.street}${valObj.business}`;
```

然后再通过百度地图提供的`Geocoder`类中的`getPoint`方法，将拼接好的`target`传入，取得经纬度。
关于`Geocoder`的用法可以看下：
[https://github.com/jser-club/rc-bmap/blob/d4122397ee625fd158f51e8fd55c79f880ddea76/src/core/utils/map.js#L168#L179](https://github.com/jser-club/rc-bmap/blob/d4122397ee625fd158f51e8fd55c79f880ddea76/src/core/utils/map.js#L168#L179)

**Comment by zxyty** [comment]
> 这里可以通过`onconfirm`中的`e`取得所选地址：
> 
> ```
> cosnt valObj = e.item.value;
> const target = `${valObj.province}${valObj.city}${valObj.district}${valObj.street}${valObj.business}`;
> ```
> 然后再通过百度地图提供的`Geocoder`类中的`getPoint`方法，将拼接好的`target`传入，取得经纬度。
> 关于`Geocoder`的用法可以看下：
> https://github.com/jser-club/rc-bmap/blob/d4122397ee625fd158f51e8fd55c79f880ddea76/src/core/utils/map.js#L168#L179

非常感谢，找到了！
