### ISSUE TITLE
官方文档部分内容缺失或者显示异常

### ISSUE THREAD

**Issue by gengdz** [jser-club/rc-bmap#84]
@JserWang 1.0版本很赞。今天早上我在http://jser.wang/bmap/。
看文档的时候发现里面的Constants部分好像出现了点问题。截图如下。
![image](https://user-images.githubusercontent.com/41912568/51506298-a8bc1600-1e26-11e9-939e-37a8ce62ebde.png)

另外基础组件Map的API文档缺失

**Comment by JserWang** [comment]
@gengdz 嗨，文档部分只是为了配合源码的发布上了大部分内容，文档会在本周不断的完善，会添加后续版本计划以及源码设计思路等等。

**Comment by JserWang** [comment]
@gengdz 关于`Size`的用法，是没有问题的，`Size`的默认`name`为`size`所以第一个`name="size"`可以不用写。
另外关于折线上箭头偏移的问题，我尝试了下百度官方的示例，也存在同样的问题… 我以上报给百度官方，如果他们没有解决方案的话，我会尝试自己实现一个`IconSequence`。

**Comment by JserWang** [comment]
文档已更新补全。
