### ISSUE TITLE
怎么清除覆盖物

### ISSUE THREAD

**Issue by gengdz** [jser-club/rc-bmap#87]
@JserWang 嗨
![image](https://user-images.githubusercontent.com/41912568/51583543-10985c80-1f0c-11e9-8952-9802bb5afe41.png)
文档上说可以调用map.clearOverlays()方法清除覆盖物，那么具体是怎么操作呢。最好能有代码演示。
旧版本是  window.bMapInstance.clearOverlays();这么操作的。那么新版本呢

**Comment by JserWang** [comment]
嗨，感谢你的提醒。在新版本中道理还是不变的

```
handleClear =() => {
    // 这里我们通过name,将实例化后的map放置global对象中。
    window.myMap.clearOverlays();
}

<Map name="myMap">
{ // ... }
</Map>
```

**Comment by FishLuo1992** [comment]
我在react的dva中使用，获取了map实例但没看到clearOverlays()这个api，蛋疼了。

**Comment by JserWang** [comment]
@FishLuo1992 @gengdz `rc-bmap`初始化后，通过传递的`name`属性将百度地图实例存储在全局对象中，方便其他地方使用。

而clearOverlays 是`Baidu.Map`对象中原有的方法，可以浏览百度地图官方文档。打印map实例后，可以通过对象原型链往下看，你会发现`clearOverlays`以及更多其他使用方法，不过我还是推荐在需要操作百度地图原生对象时，通过百度地图官方文档提供的方法使用。

[http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference_3_0.html](http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference_3_0.html)

**Comment by Oscar-ren** [comment]
理论上不渲染这个组件，这个组件就应该被自动 clear 掉，我在使用该库过程中发现了 clear 的一个 bug，已经提了 pr https://github.com/jser-club/rc-bmap/pull/93
经测试渲染多个 Marker、Point、Polyline 均能自动 clear
