### ISSUE TITLE
使用Boundary行政区域组件时，出现了前一个区域的边界线没有清除问题，导致显示错乱。

### ISSUE THREAD

**Issue by FishLuo1992** [jser-club/rc-bmap#89]
需求：动态选择省下面的市，Boundary的name动态改变。问题：当选中第二个开始，前面的行政区域的覆盖物和边界线没有清除。

有方法能每次更新都清楚前面的Boundary视图层吗？

**Comment by JserWang** [comment]
> 需求：动态选择省下面的市，Boundary的name动态改变。问题：当选中第二个开始，前面的行政区域的覆盖物和边界线没有清除。
> 
> 有方法能每次更新都清楚前面的Boundary视图层吗？

@FishLuo1992  嗨，能否在 [https://codesandbox.io](https://codesandbox.io) 中给我一个demo？选择第二个后，第一个没有清除？另外，你当前使用的`rc-bmap`的版本是？

也许你给我部分代码片段，有助于帮助我来解决你遇到的问题。

**Comment by FishLuo1992** [comment]
`import React,{ Component } from 'react';
import { Map,Boundary } from 'rc-bmap';
import Linkage from './components/linkageForm'
import  styles  from './common.less';
 export default class ChartsTest extends Component{
   constructor(props){
      super(props)
      this.state ={
        siteName:'广东省',
        selectCity:'',
      }
   }

  // 选择城市
  handleCityChange=(value)=>{
    const siteName = `广东省${value}`
    this.setState({siteName,selectCity:value})
  }

  renderSearchForm =()=>{
    return (
      <div className={styles.areaBox}>
        <Linkage
        handleCityChange={(value) =>{this.handleCityChange(value)}}
        />
      </div>
    )
  }

  renderBoundary = (siteName)=>{
    return (
      <Boundary
      name={siteName}
      autoViewport={true}
      strokeColor="blue"
      fillColor="green"
      strokeWeight={5}
      strokeOpacity={0.4}
      fillOpacity={0.1}
      strokeStyle="dashed"
      massClear={true}
      editing={false}
    />
    )
  }

  render() {
    const { siteName } = this.state
    return (
      <div className={styles.mapcontainer}>
        <Map
        name="testMap"
        ak="XXX"
        zoom={12}
       >
          {this.renderSearchForm()}
          {this.renderBoundary(siteName)}
        </Map>
      </div>
    );
  }
}`

Linkage是我定义省下面的市下拉选择和搜索的Form表单组件，选中后需要更改行政区域。 rc-bmap是"rc-bmap": "^1.0.1"。

**Comment by JserWang** [comment]
感谢提供，
目前你可以通过`React`的渲染机制，为`Boundary`给一个`key`来进行强制更新，这种写法会在`rc-bmap`中的下个版本进行优化。

``` javascript
renderBoundary = (siteName) => {
 return (
   <Boundary 
      key={`Boundary_${siteName}`}
      name={siteName}
      ...
   />
 )
}
```

**Comment by JserWang** [comment]
现在你可以升级至`1.0.2`体验。

**Comment by FishLuo1992** [comment]
感谢大佬。
