### ISSUE TITLE
清除覆盖物后再次渲染 Marker 无效果

### ISSUE THREAD

**Issue by Oscar-ren** [jser-club/rc-bmap#92]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
调用 map.clearOverlays() 清除覆盖物后，数据更新重新渲染 Marker，但是 Point 和 Polyline 都不显示了

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run. Paste the link to your CodeSandbox (https://codesandbox.io/s/jnnxrwq5y3) example below:**

- 先用数据画几个点
- 没有数据时 map.clearOverlays
- 之后来新数据，点没有画出来

**What is the expected behavior?**
期望没有数据自动清除覆盖物，数据变化覆盖物时时变化

**Comment by Oscar-ren** [comment]
我研究了一下为什么数据清空，覆盖物还存在的问题
https://github.com/jser-club/rc-bmap/blob/f61a688ea9b9f2608f84e1970f791f55e864c864/src/components/Base/Path.js#L63-L65

看这块代码，每次 point unmount 时 removePoint(index)，批量移除时 index 会篡位置。
removePoint 时 this.items 变化不会触发 path 组件重渲染，导致 point 组件的 index 不变，比如有 15 个 point，按顺序移除，会导致移除到 index === 8 的时候，this.items.length === 7，8 之后的 point 都不会被 remove 了。

**Comment by JserWang** [comment]
嗨，感谢PR，周末会统一review。
