### ISSUE TITLE
Lable bug

### ISSUE THREAD

**Issue by yufengtan** [jser-club/rc-bmap#98]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run. Paste the link to your CodeSandbox (https://codesandbox.io/s/jnnxrwq5y3) example below:**
![image](https://user-images.githubusercontent.com/25997227/54014818-c962e400-41b8-11e9-9156-ac20dd8ac798.png)
![image](https://user-images.githubusercontent.com/25997227/54014823-cc5dd480-41b8-11e9-96c4-2e5e9acb9c00.png)
![image](https://user-images.githubusercontent.com/25997227/54014868-ea2b3980-41b8-11e9-8326-d508a4725820.png)

**What is the expected behavior?**

**Comment by yufengtan** [comment]
![image](https://user-images.githubusercontent.com/25997227/54014915-1d6dc880-41b9-11e9-84db-a944a2e28589.png)

**Comment by codepandy** [comment]
content不支持jsx语法，只支持字符串，如果要传html，需要传html字符串。
"<div>123</div>"

**Comment by yufengtan** [comment]
我把版本 降到 1.0.0 貌似 是可以的啊但是我不确定 有可能是哪个 依赖包的版本影响的

**Comment by Dogtiti** [comment]
@yufengtan  我之前也是好好的 然后突然也变成这样了

**Comment by mxpup** [comment]
有解决吗各位？

**Comment by mxpup** [comment]
> content不支持jsx语法，只支持字符串，如果要传html，需要传html字符串。
> `"<div>123</div>"`

不行啊

**Comment by codepandy** [comment]
@mxpup 你是什么版本，怎么写的？
我用的是0.2.4版本，是这么实现的，没有问题。

**Comment by mxpup** [comment]
> @mxpup 你是什么版本，怎么写的？
> 我用的是0.2.4版本，是这么实现的，没有问题。

v：1.0.0

const test = `"<span>1111111</span>"`;

 <Marker animation={ANIMATION.BOUNCE}>
                    <Point lng={lng} lat={lat} />
                    <Label>
                      <Content className={"mxp"}>
                        {test}
                      </Content>
                    </Label> 
                  </Marker>

**Comment by mxpup** [comment]
> > @mxpup 你是什么版本，怎么写的？
> > 我用的是0.2.4版本，是这么实现的，没有问题。
> 
> v：1.0.0
> 
> const test = `"<span>1111111</span>"`;
> 
```
 <Marker animation={ANIMATION.BOUNCE}>
                    <Point lng={lng} lat={lat} />
                    <Label>
                      <Content className={"mxp"}>
                        {test}
                      </Content>
                    </Label>
                  </Marker>
`

**Comment by yufengtan** [comment]
把版本 降低就可以了  可以直接写 dom 无需字符串html

**Comment by yufengtan** [comment]
![image](https://user-images.githubusercontent.com/25997227/55064589-33362580-50b5-11e9-892e-d90c235dfd1f.png)
![image](https://user-images.githubusercontent.com/25997227/55064619-42b56e80-50b5-11e9-8872-e3766aae9149.png)

**Comment by mxpup** [comment]
> 把版本 降低就可以了 可以直接写 dom 无需字符串html

好使~~
